### ISSUE TITLE
`Options` in menu is disabled, unable to see settings for pitch or speed.

### ISSUE THREAD

**Issue by ncfausti** [wavenet-for-chrome/extension#18]

**Comment by ncfausti** [comment]
Inspect Popup allowed me to access settings.

**Comment by adithyabsk** [comment]
@ncfausti How did you do that? I'd like to be able to change the speed / pitch as well. Can you drop a screenshot in here?

**Comment by ncfausti** [comment]
I just right-clicked on 'Inspect popup' and it worked for me.

**Comment by adithyabsk** [comment]
Got it, thank you @ncfausti
