### ISSUE TITLE
I love this app.

### ISSUE THREAD

**Issue by azoeart** [wavenet-for-chrome/extension#30]
I love, love this app. I struggle to read and having Wavenet as an option is fantastic. Though I think that by the time I've listened to a novel it may cost the same as buying the audio version. LOL

Anyhow, would love to see this ported out of chrome into a desktop app that could read text copied to the clipboard automatically. Be even more useful if it displayed and highlighted the text in a pop-up window.

Thank you for your work!

**Comment by beldin222** [comment]
@azoeart This is probably most useful for texts that don't have an audio version, since audio books are always going to outperform Wavenet.

**Comment by azoeart** [comment]
@beldin222 You are absolutely correct. 

I use OCR+TTS mostly for reading textbooks and research material. Textbooks have some TTS capability but I'm dependent on whatever vendors decide is best/are willing to implement. Having TTS options helps keeps reading fresh. It's surprising how a new voice or TTS engine can help nudge you back into that research paper that was putting you to sleep. LOL
