### ISSUE TITLE
Adding the extension 

### ISSUE THREAD

**Issue by soheil191** [wavenet-for-chrome/extension#40]
Greetings,

Unfortunately, it is not possible to add Wavenet from the Chrome Store and also manually from the extension development methods. It gives some sort of certificate error.

Also, because I have this extension on Chromium as well, I receive a new sort of error that states the API key is not valid which is wrong, and after copy-pasting it multiple times it works.

As very handy as this extension, it will be appreciated in advance if you would fix the issue.

Thank you very much.

**Comment by pgmichael** [comment]
Hi @soheil191,

Thanks for the details.

After yesterday's update, the extension doesn't appear in the chrome web store anymore and I cannot connect to my developer dashboard.

I've contacted the chrome web store support team to understand more about this, but at the moment it looks like the extension was booted off chrome.

I'll report back when I have a better understanding of the situation.

**Comment by pgmichael** [comment]
Extension appears to be back up, although I'm still waiting for an explanation from the Chrome Web Store support team.
