### ISSUE TITLE
`npm run build` does not work on Ubuntu 18.04 

### ISSUE THREAD

**Issue by ccosnett** [wavenet-for-chrome/extension#43]
Hi, I love this package and I use it everyday! It changed my life. I wanted to modify it this morning but I ran into the following error when I tried to `npm run watch`

**Note**
- Ubuntu 18.04
- node v8.10.0
- npm v3.5.2

**My Error**

    npm ERR! Linux 4.15.0-140-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    npm ERR! node v8.10.0
    npm ERR! npm  v3.5.2

    npm ERR! Invalid version: "5"
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/conor/Dropbox/07_liquidity/18_wavenet_for_chrome/wavenet-for-chrome/extension/npm-debug.log

oh and here is the `npm-debug.log`

    (py383) ➜  extension git:(master) ✗ cat npm-debug.log 
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
    2 info using npm@3.5.2
    3 info using node@v8.10.0
    4 verbose stack Error: Invalid version: "5"
    4 verbose stack     at Object.fixVersionField (/usr/share/npm/node_modules/normalize-package-data/lib/fixer.js:191:13)
    4 verbose stack     at /usr/share/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
    4 verbose stack     at Array.forEach (<anonymous>)
    4 verbose stack     at normalize (/usr/share/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
    4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:338:5)
    4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
    4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:300:12
    4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
    4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
    5 verbose cwd /home/conor/Dropbox/07_liquidity/18_wavenet_for_chrome/wavenet-for-chrome/extension
    6 error Linux 4.15.0-140-generic
    7 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    8 error node v8.10.0
    9 error npm  v3.5.2
    10 error Invalid version: "5"
    11 error If you need help, you may report this error at:
    11 error     <https://github.com/npm/npm/issues>
    12 verbose exit [ 1, true ]

**Comment by ccosnett** [comment]
Do I need to install dependencies?

Looking in `package.json` I see

    "devDependencies": {
    "@sentry/types": "^6.2.0",
    "@types/chrome": "0.0.88",
    "copy-webpack-plugin": "^7.0.0",
    "file-loader": "^6.2.0",
    "node-sass": "^5.0.0",
    "sass": "^1.32.8",
    "sass-loader": "^11.0.1",
    "ts-loader": "^8.0.17",
    "typescript": "^3.6.2",
    "webpack": "^5.23.0",
    "webpack-cli": "^4.5.0"
      },

**Comment by pgmichael** [comment]
Hi @ccosnett

You need to run the following commands inside the terminal: `npm install` (to install the dependencies) and `npm run start` (to start the project in watch mode).

By the looks of the error message, I believe the issue is because the version inside the `package.json` file is invalid.

I wasn't aware semantic versioning was a requirement. Can you try changing `"version": "5"` to `"version": "5.0.0"` and running the start command again? 

If it's still not working, I'd try upgrading to the latest stable node release.

Let me know if that helps :)
